version: "3.7"

services:

  #databases
  setup:
    container_name: setup
    image: ghcr.io/gamify-it/test-data:latest
    pull_policy: always
    restart: on-failure
    environment:
      POSTGRES_SETUP: >
        login/default.sql
        overworld/default.sql
        chickenshock/default.sql

  login-db:
    container_name: login-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  overworld-db:
    container_name: overworld-db
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  chickenshock-db:
    container_name: chickenshock-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #backends
  login-backend:
    container_name: login-backend
    image: ghcr.io/gamify-it/login-backend:main
    restart: always
    pull_policy: always
    expose:
      - "80"
    environment:
      - JWT_KEY=SecretKEY
      - JWT_VALIDITY_DURATION=720h
      - POSTGRES_URL=postgresql://postgres:postgres@login-db:5432/

  chickenshock-backend:
    container_name: chickenshock-backend
    image: ghcr.io/gamify-it/chickenshock-backend:main
    restart: always
    pull_policy: always
    expose:
      - "80"
    depends_on:
      - chickenshock-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=postgresql://chickenshock-db:5432/postgres

  #frontends
  login-frontend:
    container_name: login-frontend
    image: ghcr.io/gamify-it/login-frontend:main
    restart: always
    pull_policy: always
    expose:
      - "80"

  chickenshock-frontend:
    container_name: chickenshock-frontend
    image: ghcr.io/gamify-it/chickenshock:main
    restart: always
    pull_policy: always
    expose:
      - "80"

  lecturer-interface:
    container_name: lecturer-interface
    image: ghcr.io/gamify-it/lecturer-interface:main
    restart: always
    pull_policy: always
    expose:
      - "80"

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.nginx/compose/nginx-dev-e2e.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/var/www/html/overworld
      - ./.nginx/style.css:/var/www/html/overworld/TemplateData/style.css
    ports:
      - "80:80"
