using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum TileSprite
{
    UNDEFINED,

    //Cave tiles
    CAVE_FLOOR,
    CAVE_WALL_BOTTOM_LEFT,
    CAVE_WALL_BOTTOM_MID,
    CAVE_WALL_BOTTOM_RIGHT,
    CAVE_WALL_TOP_LEFT,
    CAVE_WALL_TOP_MID,
    CAVE_WALL_TOP_RIGHT,
    CAVE_VOID_BOTTOM_LEFT,
    CAVE_VOID_BOTTOM_MID,
    CAVE_VOID_BOTTOM_RIGHT,
    CAVE_VOID_MID_LEFT,
    CAVE_VOID_MID_MID,
    CAVE_VOID_MID_RIGHT,
    CAVE_VOID_TOP_LEFT,
    CAVE_VOID_TOP_MID,
    CAVE_VOID_TOP_RIGHT,

    //Beach tiles
    BEACH_FLOOR,
    BEACH_WATER,
    BEACH_CONNECTION,

    //Forest tiles
    FOREST_FLOOR,
    FOREST_TREE,

    //Savanna tiles
    SAVANNA_FLOOR_BOTTOM_LEFT_WALL,
    SAVANNA_FLOOR_BOTTOM_LEFT_WATER,
    SAVANNA_FLOOR_BOTTOM_MID,
    SAVANNA_FLOOR_BOTTOM_RIGHT_WALL,
    SAVANNA_FLOOR_BOTTOM_RIGHT_WATER,
    SAVANNA_FLOOR_MID_LEFT_WALL,
    SAVANNA_FLOOR_MID_LEFT_WATER,
    SAVANNA_FLOOR_MID_INNER_CORNER_LEFT,
    SAVANNA_FLOOR_MID_MID,
    SAVANNA_FLOOR_MID_INNER_CORNER_RIGHT,
    SAVANNA_FLOOR_MID_RIGHT_WALL,
    SAVANNA_FLOOR_MID_RIGHT_WATER,
    SAVANNA_FLOOR_TOP_LEFT,
    SAVANNA_FLOOR_TOP_MID,
    SAVANNA_FLOOR_TOP_RIGHT,
    SAVANNA_WALL_BOTTOM_LEFT,
    SAVANNA_WALL_BOTTOM_MID,
    SAVANNA_WALL_BOTTOM_RIGHT,
    SAVANNA_WALL_TOP_LEFT_WALL,
    SAVANNA_WALL_TOP_LEFT_WATER,
    SAVANNA_WALL_TOP_MID,
    SAVANNA_WALL_TOP_RIGHT_WALL,
    SAVANNA_WALL_TOP_RIGHT_WATER,
    SAVANNA_WATER
}
